version: "3.8"
services:
  web:
    build: ./
    image: 316416256946.dkr.ecr.us-east-1.amazonaws.com/onlineshopping:bookstore_image
    command: gunicorn nc_tutorials.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/
      - static_volume:/usr/src/static
    expose:
      - 9010
    environment:
      - DB_NAME=bookdatabase-1
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - DB_HOST=bookdatabase-1.c0pa5dbxh2kl.us-east-1.rds.amazonaws.com
      - DB_PORT=5432
      - DATABASE=postgres
      - VIRTUAL_HOST=ec2-34-203-123-55.compute-1.amazonaws.com
      - VIRTUAL_PORT=8000
  nginx:
    build: ./nginx
    image: 316416256946.dkr.ecr.us-east-1.amazonaws.com/onlineshopping:bookstore_image
    volumes:
      - static_volume:/usr/src/static
    ports:
      - "10080:80"
      - "10443:443"
    depends_on:
      - web
volumes:
  static_volume:
